### ISSUE TITLE
question: intent to release / open source Lunacy Engine?

### ISSUE THREAD

**Issue by knksmith57** [icons8/lunacy-docs#1]
Heya @Icons8-Team!

Huge shout out on the incredible work you've done on Lunacy and `.sketch` support and integration.

I'm super interested (and impressed!) with all the work y'all have put into parsing / mutating / (in the future) writing native Sketch files. Based on [the `Sketch.The.Ripper` site](http://sketch.the.ripper.graphics/), it sounds like the tech behind this interop functionality is called the _Lunacy Engine_; am I getting that right?

Lunacy Engine sounds like an extremely useful (and powerful!) tool that would _greatly_ benefit the OSS community and help push the state of the art for design <-> eng tooling forward (in a possibly big way).

Is there appetite / interest from Icons8 to make any part of Lunacy Engine available to the public (whether open source or not)?

Thanks again for all of your hard work and dedication to bringing `.sketch` support to Windows!

**Comment by gritsenko** [comment]
Hey @knksmith57 !
Thanks for your question!
We definitely plan to publish some parts of lunacy to open source. At least plug-in and integrations modules and api's. But at the moment we are concentrated on finishing base functionality of lunacy as vector graphics editor.

Igor
