### ISSUE TITLE
Missing Images After Closing Project

### ISSUE THREAD

**Issue by afonsolopez** [icons8/lunacy-docs#12]
If I insert any image to the project, after I close and then re-open the project again the image is invisible, but still present at the layers tab.

**Comment by gritsenko** [comment]
Thanks @afonsolopez ! We'll check it out

**Comment by gritsenko** [comment]
@afonsolopez we can't reproduce that bug. Can you send a file with not visible image to lunacy@icons8.com?

**Comment by maxinwong** [comment]
I encounter the same bug: If I insert any image to the project, after I close and then re-open the project again the image is invisible, but still present at the layers tab.

Please check the image 
![picturemessage_ybvs2x2a 1ac](https://user-images.githubusercontent.com/46342441/50630027-15f03000-0f7a-11e9-8f59-64a4a0408bc5.png)

**Comment by AndreyGrishin** [comment]
> I encounter the same bug: If I insert any image to the project, after I close and then re-open the project again the image is invisible, but still present at the layers tab.
> 
> Please check the image
> ![picturemessage_ybvs2x2a 1ac](https://user-images.githubusercontent.com/46342441/50630027-15f03000-0f7a-11e9-8f59-64a4a0408bc5.png)

Hello.
If you have any errors while working with the application, please describe the problem on the project forum https://community.icons8.com/c/lunacy

**Comment by sergeychekmenev** [comment]
Hello! Thank you for your cooperation and interest to our project. We would appreciate it if you join our community forum on this page: https://community.icons8.com. Tons of useful info is already available on the forum! Bugs fixes, issues, discussions, announcements, articles, tips, links to videos, anticipated features, improvements. All hot topics in one place! Be a part of the community! Report bugs and join discussions! Help less experienced users! Access the most recent builds and send us documented feedback!

**Comment by vganjali** [comment]
Hello, I have the same random behavior on missing images once in a while. For me, it does happen even I keep the file open. My guess is this bug is something related to the saving process. The image placeholder is there, but the content of the image disappears.

**Comment by sourcetreehugger** [comment]
I too have missing images after opening / closing the file, sometimes.

Other images are still present but the reference to a particular image is sometimes broken, resulting in a gray area where the image used to be. 

I'm on version 9.1.1

**Comment by molumen** [comment]
Still happening in version 10.3 and 10.4 (just upgraded to it).
I open the file and see placeholders of photos that were previously imported. I can use CTRL+J and reload the photos back, and save the file. Closing it and reopening it, and the photos are gone. Some times one of the photos is there, some other time another photo is there, some times all photos are gone.
[tests.zip](https://github.com/user-attachments/files/17387531/tests.zip)

All photos are listed in the layers. File size suggests that the photos' information is there, just not rendering for some reason.
The preview shows the photos in their correct places.

**Comment by Mikolaytis** [comment]
@molumen please contact support by "Help -> report a problem", including logs and device info. I will look into it.
