### ISSUE TITLE
Error while openning file

### ISSUE THREAD

**Issue by Luckycn** [icons8/lunacy-docs#15]
When I open a .sketch file, something is wrong
![image](https://user-images.githubusercontent.com/4628573/43498455-9b59ede2-9579-11e8-8161-e3abd845ea68.png)

And my lunacy version is:
![image](https://user-images.githubusercontent.com/4628573/43498790-1dc0502c-957b-11e8-8336-d0723c2396df.png)

**Comment by gritsenko** [comment]
Hello @Luckycn! Can you provide sketch file?

**Comment by sergeychekmenev** [comment]
Hello! We would appreciate it if you join our community forum on this page: https://community.icons8.com. Tons of useful info is available there! Bugs fixes, issues, discussions, announcements, articles, tips, links to videos, anticipated features, improvements. All hot topics in one place! Be a part of the community! Report bugs and join discussions! Help less experienced users! Access the most recent builds and send us documented feedback!
