### ISSUE TITLE
Error when opening file.

### ISSUE THREAD

**Issue by GHXST01** [icons8/lunacy-docs#16]
Not sure if this is the right place to report bugs, but it seemed somewhat fitting so I'm going to give it a try.

- Version used: LunacyPortable 3.8 x64
- Operating system: Windows 10 x64
- Reproducibility: 100% on my system

Error:
![image](https://user-images.githubusercontent.com/24251238/44002761-5a6300d0-9e48-11e8-855f-446660a8b8de.png)

Sketch file:
[MI Creative Agency Free Sketch.zip](https://github.com/icons8/lunacy-docs/files/2281015/MI.Creative.Agency.Free.Sketch.zip)

**Comment by AndreyGrishin** [comment]
Thanks for the feedback. 
In the next release we will try to fix this problem.

**Comment by flytam** [comment]
@AndreyGrishin 

> Thanks for the feedback.
> In the next release we will try to fix this problem.
Hi , Is this fixed？

**Comment by AndreyGrishin** [comment]
In version 3.14 the file should open correctly.
https://a.icons8.com/jiWZgUXL/egQWSI/image.png

**Comment by sergeychekmenev** [comment]
We would appreciate it if you join our community forum on this page: https://community.icons8.com. Tons of useful info is available there! Bugs fixes, issues, discussions, announcements, articles, tips, links to videos, anticipated features, improvements. All hot topics in one place! Be a part of the community! Report bugs and join discussions! Help less experienced users! Access the most recent builds and send us documented feedback!
