### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by xeijin** [icons8/lunacy-docs#17]
Hello, could you please provide a license doc for Lunacy? I have been unable to locate one. Many thanks!

**Comment by visualpharm** [comment]
Here we go: https://github.com/icons8/lunacy-docs/blob/master/docs/lunacy%20license.md
Thanks for the tip.

**Comment by xeijin** [comment]
@visualpharm Thank you, one additional question - it wasn’t 100% clear to me from the EULA, it seems to imply that Lunacy is free for evaluation use, but doesn’t explicitly mention a non-evaluation/ongoing or operational use-case. Can you confirm if Lunacy is 100% free for on-going, operational use?

**Comment by xeijin** [comment]
@visualpharm would you be able to confirm on the question above? Many thanks.

**Comment by visualpharm** [comment]
Sure! It's 100% free for the ongoing operational use.
