### ISSUE TITLE
Text properties not visible with multiple Text Areas

### ISSUE THREAD

**Issue by UTurista** [icons8/lunacy-docs#2]
When selecting multiple Text Areas, the text properties - Font, color, size, weight, etc - stop being present. Preventing us to quickly edit multiple texts with common properties.

The same way we can edit "Fills", "Stroke" or "Shadows" for multiple shapes we should be able to do the equivalent for text.

**Comment by sergeychekmenev** [comment]
Hello, we do appreciate your interest to our project. The group editing of text block settings is not available at the moment. However we do plan to implement it the most upcoming releases. In the mean time, we recommend you to try out the alpha version (3.15.0.1). We would appreciate it if you join our community forum on this page: https://community.icons8.com. Tons of useful info is already available on the forum! Bugs fixes, issues, discussions, announcements, articles, tips, links to videos, anticipated features, improvements. All hot topics in one place! Be a part of the community! Report bugs and join discussions! Help less experienced users! Access the most recent builds and send us documented feedback!
