### ISSUE TITLE
Cannot launch Lunacy

### ISSUE THREAD

**Issue by hentrytan** [icons8/lunacy-docs#23]
Everytime I tried to launch lunacy, neither with portable or I installed it first. I got the same error message. 
This is the error message that I recieved:

![capture](https://user-images.githubusercontent.com/43266615/45541237-b5a57900-b838-11e8-8dc6-5b17c67abd0a.JPG)

Can someone help me in this issue? Thankyou.

Regards,

Hentry

**Comment by AndreyGrishin** [comment]
If you use the portable version, you will need VC++ redistributable 2015 and Net Framework 4.6.1 installed.
https://www.microsoft.com/en-us/download/details.aspx?id=48145
https://www.microsoft.com/en-us/download/details.aspx?id=49981

Try to describe your problems here https://community.icons8.com/c/lunacy

**Comment by hentrytan** [comment]
Hi Andrey,

Thank you for your response.
I'm currently using windows 8.0. I tried portable and Installer version. Both of them gave me the same error message. I just posted the problem in icons8 community. Thank you so much.

Regards,

Hentry

**Comment by sergeychekmenev** [comment]
That is great Henry! Community is a great place to share ideas! Thank you for cooperation and your interest to our project!
