### ISSUE TITLE
Error while openning file. 

### ISSUE THREAD

**Issue by RobertM197** [icons8/lunacy-docs#25]
Hello,

first many thanks for the cool program Lunacy.
Unfortunately, I got a problem after 5 days of work.
When opening the .sketch file, a pop-up window appears where you can: Can't open file. wrong format or internal error.
.....

I hope you can help me because I've already put a lot of work into it.

Thanks in advance.
Robert :)

Lunacy Version: 3.13.20

The Link to my .sketch: [https://we.tl/t-ZwOmhyX0Jj](url)

**Comment by AndreyGrishin** [comment]
Hello. This file is corrupt and cannot be opened even in Sketch.
