### ISSUE TITLE
Missing icon font

### ISSUE THREAD

**Issue by kumold** [icons8/lunacy-docs#26]
In my sketch file I use Google's Material Icons. But when I open said sketch file in Lunacy, only ligatures are shown and when I select element with them, Lunacy crashes.
Icon font file is installed in Windows.

![screenshot_1](https://user-images.githubusercontent.com/489406/49848607-0dd02500-fe00-11e8-998c-3ca9159caf65.png)

**Comment by sergeychekmenev** [comment]
Hello! Please, try out the alpha version and let us know if the problem would remain. We would appreciate it if you join our community forum on this page: https://community.icons8.com and republish the issue there if it will actually be replicated on the alpha build. Tons of useful info is already available on the forum! Bugs fixes, issues, discussions, announcements, articles, tips, links to videos, anticipated features, improvements. All hot topics in one place! Be a part of the community! Report bugs and join discussions! Help less experienced users! Access the most recent builds and send us documented feedback!

**Comment by sergeychekmenev** [comment]
In the mean time could you please let us know what the Font you are using?

**Comment by kumold** [comment]
I'm using Google's Material Icon font

**Comment by kumold** [comment]
Tested in latest version from Microsoft Store. Still showing error.

**Comment by sergeychekmenev** [comment]
Hello! We do accept that the Microsoft Store version has this bug with the font. As for now, we recommend you to switch to the portable version or the windows installer. You may download them directly from here: https://icons8.com/lunacy

**Comment by sergeychekmenev** [comment]
We would appreciate it if you join our community forum on this page: https://community.icons8.com. Tons of useful info is available there! Bugs fixes, issues, discussions, announcements, articles, tips, links to videos, anticipated features, improvements. All hot topics in one place! Be a part of the community! Report bugs and join discussions! Help less experienced users! Access the most recent builds and send us documented feedback!
