### ISSUE TITLE
language selection is invalid

### ISSUE THREAD

**Issue by fxxxxxmio** [icons8/lunacy-docs#28]
Regardless of which country to choose language, is still displayed in English
![20181224150539](https://user-images.githubusercontent.com/46100330/50393311-60122e00-0790-11e9-8b93-8f5a1f325ca8.png)
![20181224152121](https://user-images.githubusercontent.com/46100330/50393313-60aac480-0790-11e9-9a4f-368d7c3d69f1.png)

**Comment by AndreyGrishin** [comment]
Hello.
Do you have a single language version of Windows installed?

**Comment by fxxxxxmio** [comment]
> Hello.
> Do you have a single language version of Windows installed?

English(US) & Chinese , But whatever I choose which is the same situation
![20181224172913](https://user-images.githubusercontent.com/46100330/50396018-1c282480-07a2-11e9-83b3-5d52dd1a84cb.png)

**Comment by AndreyGrishin** [comment]
Do you change the language in the application?
https://a.icons8.com/ffabftXi/Htwet2/2019-01-21_13-12-48.png

**Comment by sergeychekmenev** [comment]
Hello, thank you for your interest to our project and cooperation! In regard to the issue, please note that there is a Language section in the main menu. The content of that section is responsible for the localization of the app. Also we would appreciate it if you join our community forum on this page: https://community.icons8.com. Tons of useful info is already available on the forum! Bugs fixes, issues, discussions, announcements, articles, tips, links to videos, anticipated features, improvements. All hot topics in one place! Be a part of the community! Report bugs and join discussions! Help less experienced users! Access the most recent builds and send us documented feedback!
