### ISSUE TITLE
can not open skecth file in window 10 1809

### ISSUE THREAD

**Issue by badboy-tian** [icons8/lunacy-docs#29]
![image](https://user-images.githubusercontent.com/2835129/51361843-443e4580-1b0c-11e9-80dd-02d52f7e1ada.png)
![image](https://user-images.githubusercontent.com/2835129/51361859-4ef8da80-1b0c-11e9-9fd1-4335aed0182a.png)
![image](https://user-images.githubusercontent.com/2835129/51361864-51f3cb00-1b0c-11e9-95e3-d172cb1f9e6d.png)

**Comment by sergeychekmenev** [comment]
Hello! Thank you for cooperation and your interest to our project! Could you please provide some more info on what circumstances it happens. Please share the file that actually causes the problem! We would appreciate it if you join our community forum on this page: https://community.icons8.com and publish this issue there. Tons of useful info is already available on the forum! Bugs fixes, issues, discussions, announcements, articles, tips, links to videos, anticipated features, improvements. All hot topics in one place! Be a part of the community! Report bugs and join discussions! Help less experienced users! Access the most recent builds and send us documented feedback!
