### ISSUE TITLE
Windows scaling issue

### ISSUE THREAD

**Issue by Rogue85** [icons8/lunacy-docs#3]
Toolbar is hidden over the viewport when Windows 10 UI scaling is not 100%.

![default](https://user-images.githubusercontent.com/6161136/40580501-3def7038-6148-11e8-8712-e36371ff1ccd.png)

**Comment by gritsenko** [comment]
Thanks! We'll fix it

**Comment by AndreyGrishin** [comment]
Was fixed in version 3.8.0
