### ISSUE TITLE
Crashing when using text tool

### ISSUE THREAD

**Issue by EllieG101** [icons8/lunacy-docs#30]
Every time I try to use the text tool the application crashes & closes.

Is there anything I can do to stop this?

**Comment by sergeychekmenev** [comment]
Hello! Thank you for your cooperation and interest to our project. Please provide some more details on the issue. At what circumstances it happens, what was the sequence of your actions etc. We would appreciate it if you join our community forum on this page: https://community.icons8.com and publish this issue there. Tons of useful info is already available on the forum! Bugs fixes, issues, discussions, announcements, articles, tips, links to videos, anticipated features, improvements. All hot topics in one place! Be a part of the community! Report bugs and join discussions! Help less experienced users! Access the most recent builds and send us documented feedback!
