### ISSUE TITLE
Problem with editing symbols and keeping instances values

### ISSUE THREAD

**Issue by jurra** [icons8/lunacy-docs#31]
Hi there! :sparkles: 
## This is the problem I am facing:
1. I create a symbol with text, say a style for text that I might one to edit later
2. I create an instance and change the text value of the symbol
3. I re-edit the symbol properties like font color, but can also be background color
4. The instance's value is changed to the symbols "default" text

**Comment by sergeychekmenev** [comment]
Hello! Sorry for the delay with reply ;o) For editing visible text within a symbol object you have to use Ctrl+mouse_dbl_click. Please use the latest version update of Lunacy. Also we would appreciate it if you join our community forum on this page: https://community.icons8.com and publish any issue there. Tons of useful info is already available on the forum! Bugs fixes, issues, discussions, announcements, articles, tips, links to videos, anticipated features, improvements. All hot topics in one place! Be a part of the community! Report bugs and join discussions! Help less experienced users! Access the most recent builds and send us documented feedback!

**Comment by jurra** [comment]
Great thanks!!!
