### ISSUE TITLE
question: offline to use

### ISSUE THREAD

**Issue by LXMin** [icons8/lunacy-docs#33]
I really like the style of icons8, but I can't find any link to download all the package to use it offline.
I need to work in the offline environment, so I can't use the icons8 API to get the icon. So I'm wondering if I can download all the icons one time, and put the downloaded folder in my react project directly to use it.

**Comment by Mikolaytis** [comment]
Hi, you can download all icons and use it offline. But to download icons once - you need to run lunacy online, go to components/icons and press "Download 500mb". After download you can use lunacy offline.

For instance if you always do not have internet on PC - you can run Lunacy at online PC, download icons and copy %user%/appdata/Icons8/Lunacy/IconsDatabase folder to USB drive and then copy DB from USB flash drive to another offline PC.

Also we have offline app with icons database included in installer. You can download it here: https://icons8.com/app
