### ISSUE TITLE
New Bugs

### ISSUE THREAD

**Issue by muhamed44** [icons8/lunacy-docs#34]
The update seem has some new bugs that doesnt exist in older version
![New Bitmap Image](https://user-images.githubusercontent.com/24223950/59718293-2fc8bb00-921a-11e9-992b-146369e3b602.png)
and this is a screen from older version 
![New Bitmap Image - Copy](https://user-images.githubusercontent.com/24223950/59718773-28ee7800-921b-11e9-9c75-f69d7b71f19e.png)

**Comment by AndreyGrishin** [comment]
Please describe your problem here https://community.icons8.com/c/lunacy/. If possible, attach the problem file so that we can solve the problem in the next releases.
