### ISSUE TITLE
How to enable the option to see margins and distances?

### ISSUE THREAD

**Issue by llkiriell** [icons8/lunacy-docs#36]
In the help document it says that the margins and distances are shown. But, I'm trying the program and it don't appear to me.

That option is not in the program?
Or how could I enable it?

**Me:**
![Me](https://images2.imgbox.com/0e/ef/6ElLHdbS_o.jpg)
**Docs:**
![Doc](https://docs.icons8.com/public/mAz4bmww76HilrhUizdqvw_img_49.png)

**Comment by Mikolaytis** [comment]
Try to hold Alt button and move mouse around

**Comment by llkiriell** [comment]
Oh, excellent. Thank you.
I tried in many ways, but not like that. Thank you.

![Margin](https://images2.imgbox.com/82/b3/QeOgQmAo_o.png)
