### ISSUE TITLE
Lunacy Soft-Lock on Artboard Duplication & Manipulation

### ISSUE THREAD

**Issue by saint-justin** [icons8/lunacy-docs#37]
# Lunacy Soft-Lock on Artboard Duplication & Manipulation

## Main Issue:
When I duplicate and then manipulate an artboard, the program soft-locks and starts cranking my CPU speeds up. 

### Screenshot
![8c97445d5fade8789655f796bf009231](https://user-images.githubusercontent.com/31663032/62843464-99e06800-bc7f-11e9-9102-b10a953cbebe.png)

## Extra Details:
I had a similar soft-lock issue a little bit prior when scrolling horizontally using a trackpad. Not quite sure if this is the proper place to submit issues/tickets but this is all I could find.

**Comment by Mikolaytis** [comment]
Hi! Thanks for reaching out. We've fixed a lot of issues and will publish a new version soon

**Comment by saint-justin** [comment]
I've hit a few more issues w/ the software soft-locking. Do you want a log of each crash or are you guys handling it internally?

**Comment by Mikolaytis** [comment]
We are not handling it internally. But we've found and fixed a lot of them so to not waste your and our time let's wait for our next release that will be today or tomorrow (4.1 version) and if soft-locks will still occur - send as logs or crash dumps!
