### ISSUE TITLE
Can't open file: wrong format

### ISSUE THREAD

**Issue by vurka25** [icons8/lunacy-docs#38]
I have got a sketch file that was opened with Sketch application on Mac (it worked perfectly) and it cannot be open with Lunacy on Windows 10. I've attached the error message

![image](https://user-images.githubusercontent.com/22756153/67017698-6d6f1f00-f0fa-11e9-96ea-f775bd4c49cb.png)

**Comment by Mikolaytis** [comment]
we cannot investigate the issue without this file.
