### ISSUE TITLE
Issue on v3.5: Missing red pixel number indicator

### ISSUE THREAD

**Issue by kringleg** [icons8/lunacy-docs#4]
Hi,

Not sure why it's not working for me anymore, but I can't make the red pixel indicator appear anymore even when I press on Alt. It was working fine for me in v3.4, but when I updated the app to v3.5, this doesn't appear anymore.

Hope you can have it fixed soon as it's really a struggle to make sure that all elements have x amount of pixels between them without this feature.

Thanks!

**Comment by gritsenko** [comment]
@kringleg Hey! Can you check out if distance indicator shown after you move cursor between objects after alt is pressed? 
I mean: 
1. select object
2. press and hold Alt key
3. move mouse over few different objects 

and let me know if red lines will shown sometime?

thanks

**Comment by kringleg** [comment]
@gritsenko Hi! Nope, unfortunately none of the red lines are showing when I click an element, hold Alt, and hover my mouse cursor over the other elements on the screen. The only time i see the red lines now are just for the snapping of elements in place, but no longer with showing the distance between each element.

Here's a sample screenshot. Mouse cursor just isn't visible but when I took this, the cursor was over the 1st paragraph.

![image](https://user-images.githubusercontent.com/39816810/40839996-71f00882-65d7-11e8-9d4e-b72c55cce175.png)

Thanks!

**Comment by whb7762300** [comment]
I have the same problem,so i still use the v3.4,but i hope this problem will be fixed

**Comment by sergeychekmenev** [comment]
Hello guys! Thank you for cooperation and your interest to our project! We would appreciate it if you join our community forum on this page: https://community.icons8.com and publish all the issues there. Tons of useful info is already available on the forum! Bugs fixes, issues, discussions, announcements, articles, tips, links to videos, anticipated features, improvements. All hot topics in one place! Be a part of the community! Report bugs and join discussions! Help less experienced users! Access the most recent builds and send us documented feedback!
