### ISSUE TITLE
The brackets for arranging objects are in reverse in the documentation.  Please update the documentation.

### ISSUE THREAD

**Issue by TazExprez** [icons8/lunacy-docs#46]
It should be:

Bring Forward: Ctrl+]
Bring to Front: Ctrl+Shift+]
Send Backward: Ctrl+[
Send to Back: Ctrl+Shift+[

Not:

Bring Forward: Ctrl+[
Bring to Front: Ctrl+Shift+[
Send Backward: Ctrl+]
Send to Back: Ctrl+Shift]

**Comment by uksla** [comment]
Fixed. Thanks!
