### ISSUE TITLE
Which programming language was using to create the Lunacy?

### ISSUE THREAD

**Issue by LeftTwixWand** [icons8/lunacy-docs#51]
Hi. I'm a developer, and interesting in new technologies.
And I was trying to find information about the programming language, which was using in the Lunacy,
Because it works really fast and looks amazing.

**Comment by Mikolaytis** [comment]
Core: C#, .Net 5.0
UI: WPF (migrating to AvaloniaUI)
Rendering: Skia->OpenGL->Angle->DirectX
