### ISSUE TITLE
Strange cursor problem on linux

### ISSUE THREAD

**Issue by eboye** [icons8/lunacy-docs#53]
![image](https://user-images.githubusercontent.com/624357/152626544-b3dfc693-fbb2-4e89-aa4f-30b9623d1208.png)

As you can see in the screenshot above, there is some strange layer below the cursor all the time.

Is there any way to remove that?

Distro: Manjaro Qonos 21.2.2
DE: Gnome 41.3
Compositor: Wayland

**Comment by vegansk** [comment]
Same problem on Linux Mint 19.3

**Comment by Flashwalker** [comment]
I have the same glitch

**Comment by Mikolaytis** [comment]
We don't know the source of the issue. Hopefully we will have a fix in 8.6
