### ISSUE TITLE
Lunacy soft won't open on ubuntu 20.04

### ISSUE THREAD

**Issue by fredhmacau** [icons8/lunacy-docs#54]
I downloaded the soft from the snap store and since the download finished, the icon in the linux environment is visible, but it doesn't start Lunacy or give any sign of loading. I've tried restarting the PC, it didn't work.

Thank you in advance!

**Comment by Mikolaytis** [comment]
Thanks for contacting us. Have you tried DEB package from a lunacy website?
Please, send us a bit info about your hardware. We have no issues on our hardware.

**Comment by fredhmacau** [comment]
I used exactly the DEB package from the lunacy website.
DEB link:
https://snapcraft.io/lunacy
My hardware specs are:
4G memory
Intel® Core™ i3-2350M CPU @ 2.30GHz × 4 processor

Intel® HD Graphics 3000 (SNB GT2)

OS Ubuntu 20.04.3 LTS
64-bit OS type

**Comment by tibring** [comment]
Hello!
@fredhmacau Could you try the latest Lunacy version?

**Comment by NealWilxite** [comment]
Hi. I'm having the same issue. Tried uninstalling and reinstalling from the Snap Store using Software (both latest/stable and latest/edge)  and the deb package from this website. (version 9.0.0). 

My specs: 
![Screenshot from 2023-03-01 13-58-12](https://user-images.githubusercontent.com/54668805/222163233-1d509667-cacc-40f4-8964-a7ea21d1b979.png)
