### ISSUE TITLE
Couldn't play the project i've worked with

### ISSUE THREAD

**Issue by ligmadig** [icons8/lunacy-docs#55]
So i am a newcomer on Ui/Ux design world and since i start my project in Lunacy, it seems that mine couldn't play it.

file:///home/afi/snap/lunacy/45/.local/share/Icons8/Lunacy/Prototyping/37e49490-1011-4022-b761-b621a347525f/index.html is not readable. It may have been removed, moved, or file permissions may be preventing access.

I use lunacy on Ubuntu, thanks.

(p.s. sorry for my bad grammar)

**Comment by tibring** [comment]
@ligmadig 
Hi!
Is this issue actual now?
