### ISSUE TITLE
lunacy can't launch on ubuntu 21.10

### ISSUE THREAD

**Issue by icychick-liu** [icons8/lunacy-docs#56]
Both deb package and snap store have the same problem, lunacy can't run after installed.
![PC_info](https://user-images.githubusercontent.com/20346851/154388791-ae1f5196-2928-4a29-82ef-a7c453916e67.png)

**Comment by benduckwdesign** [comment]
```
            .-/+oossssoo+/-.               mikudayo@kitsune 
        `:+ssssssssssssssssss+:`           ---------------- 
      -+ssssssssssssssssssyyssss+-         OS: Ubuntu 21.10 x86_64 
    .ossssssssssssssssssdMMMNysssso.       Kernel: 5.13.0-37-generic 
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Uptime: 2 hours, 17 mins 
  +ssssssssshmydMMMMMMMNddddyssssssss+     Packages: 2612 (dpkg), 71 (flatpak), 10 (snap) 
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Shell: bash 5.1.8 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Resolution: 3840x2160, 2560x1440 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   DE: GNOME 40.5 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   WM: Mutter 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   WM Theme: gnome-professional-40.1-dark 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Theme: gnome-professional-40.1-dark [GTK2/3] 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Icons: WhiteSur-dark [GTK2/3] 
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/    Terminal: gnome-terminal 
  +sssssssssdmydMMMMMMMMddddyssssssss+     CPU: AMD Ryzen 9 3900XT (24) @ 4.000GHz 
   /ssssssssssshdmNNNNmyNMMMMhssssss/      GPU: NVIDIA GeForce RTX 2070 
    .ossssssssssssssssssdMMMNysssso.       GPU: NVIDIA GeForce GT 710 
      -+sssssssssssssssssyyyssss+-         Memory: 7117MiB / 128723MiB 
        `:+ssssssssssssssssss+:`
            .-/+oossssoo+/-.                                       
```
I see a couple errors / warnings about fonts though with conf.d and there's weird GPU artifact bugs around the mouse, but the GPU artifacts may just be NVIDIA proprietary drivers acting up. Other than that the snap works for me on Ubuntu 21.10.

What didn't work for me however was the flatpak but I haven't seen any note of it on the website, so I'm unsure whether that's supposed to be an official option or not; it's based on the deb regardless. Flatpak crashes shortly after launch with a stack trace about `Unhandled exception. System.InvalidOperationException: Default font family name can't be null or empty.`.

Is there anything in the console you can post that appears after you run it? Have you tried uninstalling the snap and reinstalling it?

**Comment by benduckwdesign** [comment]
> @benduckwdesign Hi! Could you try the latest version of Lunacy. It should be free of the font issue.

Just updated all of my flatpaks, issue is still occurring. Same trace as I mentioned from the other issue.

```
Unhandled exception. System.InvalidOperationException: Default font family name can't be null or empty.
   at Avalonia.Media.FontManager..ctor(IFontManagerImpl platformImpl)
   at Avalonia.Media.FontManager.get_Current()
...
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode)
   at Lunacy.Program.Main(String[] args) in /builds/lunacy/lunacy/Lunacy/Lunacy/Program.cs:line 16
```

I am now on `Ubuntu 22.04 LTS x86_64` so this may have affected any presumed results. Flatpak of Lunacy is on version `8.5.2` from `org.flathub.Stable` which was last updated on `2022-06-15`. If there is a newer version of Lunacy that you would like me to test than `8.5.2` then we will have to wait for it to refresh in the flatpak distribution.

**Comment by benduckwdesign** [comment]
Still happening with `9.0.9`, same `Unhandled exception. System.InvalidOperationException: Default font family name can't be null or empty.`, with trace leading back to `Lunacy.Program.Main(String[] args) in /builds/lunacy/lunacy/Lunacy/Lunacy/Program.cs:line 16`.

**Comment by Mikolaytis** [comment]
https://github.com/AvaloniaUI/Avalonia/issues/4427#issuecomment-669173654
<img width="980" alt="Screenshot 2023-04-13 at 00 59 59" src="https://user-images.githubusercontent.com/4997065/231595318-95a322fc-e15e-4721-ad6d-5ca9ffc2f81a.png">

**Comment by Mikolaytis** [comment]
I will make a possible hotfix now. You can test it in beta build, available here:
### Beta

* Windows [exe64beta](https://lcdn.icons8.com/setup/beta/LunacySetup.exe)
* Windows [exeARMbeta](https://lcdn.icons8.com/setup/beta/LunacySetup_arm64.exe)
* MacOS [dmgBeta](https://lcdn.icons8.com/setup/beta/Lunacy.dmg)
* MacOS [pkgBeta](https://lcdn.icons8.com/setup/beta/Lunacy.pkg)
* Linux [deb64beta](https://lcdn.icons8.com/setup/beta/Lunacy.deb)
* Linux [debARMbeta](https://lcdn.icons8.com/setup/beta/Lunacy.ARM.deb)

**Comment by mtnzorlu** [comment]
Some bugs may have been fixed.
Lunacy icon appears small (LunacyLogo.png)
