### ISSUE TITLE
CTRL + Backspace disable typing in text boxes.

### ISSUE THREAD

**Issue by n0ct3ri4** [icons8/lunacy-docs#57]
Hello! I finded a little bug in Lunacy (8.2.1 MS Store Edition).

When I'm writing in a text box and pressing the **CTRL + Backspace** keys, Lunacy doesn't allow me to write anymore. I can still select objects, move them, etc... but I can't write. 

It's a combinaison that I'm using for a _looong_ time (because I'm a developer), and I need this issue to be patched :(

Thank you, this software is a lifechanger tho 👍🏽 

**EDIT** : I still can write via reopening the app.

**Comment by Mikolaytis** [comment]
Hi, thanks for contacting us. We've searching for the source of the hotkeys disabling issue for a long time. Thanks for helping us to find the source of the issue. We will fix this in 8.4 after our QA investigation. 8.3 released yesterday. 8.4 will be released in two weeks +-
