### ISSUE TITLE
Italic fonts?

### ISSUE THREAD

**Issue by tipsy** [icons8/lunacy-docs#59]
Most editors (and browsers) "italicize" the font if there's no italic version, does Lunacy not support this? I'm unable to do anything with CTRL+I, and I can't find a setting for it.

**Comment by Mikolaytis** [comment]
this is called oblique. Actually a nice idea. I will put it on our next team meeting.


This is not our request features tracker. Here we accept only documentation-related issues.
This is our request features forum: https://lunatics.icons8.com/discussions
