### ISSUE TITLE
Title case for the text in the text options doesn't work

### ISSUE THREAD

**Issue by sarah27h** [icons8/lunacy-docs#60]
I added the title case style for text but after saving the project and reopening it I found the text returned to lowercase again.

![bug](https://user-images.githubusercontent.com/25668830/193477735-a61acf2a-1bef-4ab5-b7d9-53658b36ee2f.png)

**Comment by Mikolaytis** [comment]
This is not our bug tracker. Here we accept only documentation-related issues.
Please, report new bugs here: https://community.icons8.com/c/lunacy/7

About issue - I hope it fixed in the recent updates. If not - contact as via community forum. Thanks!
