### ISSUE TITLE
When switching to simplified Chinese, menu bar fonts are not aligned

### ISSUE THREAD

**Issue by yudong2ao** [icons8/lunacy-docs#66]
When I adjust the language to simplified Chinese, the text of the menu bar is not aligned, but in the traditional Chinese menu bar text is also central, and I think the problem is that the Chinese font of lunacy in the Windows system has not chosen Microsoft's black cause
![image](https://user-images.githubusercontent.com/59545510/200985166-a0f629a4-cea9-47e2-9bdd-48839dc2ea7c.png)

**Comment by blueyms** [comment]
how to getting start from chinese document ? learn from chinese maybe is awasone.

**Comment by Mikolaytis** [comment]
This is not our bug tracker. Here we accept only documentation-related issues.
Please, report new bugs here: https://community.icons8.com/c/lunacy/7

About issue - I hope it fixed in the recent updates. If not - contact as via community forum. Thanks!
