### ISSUE TITLE
NaN Error when creating a vertical and/or a horizontal line

### ISSUE THREAD

**Issue by mrivera301** [icons8/lunacy-docs#7]
1. There appears to be a problem with creating horizontal and vertical lines. This error only seems to appears when scaling the line (which show the width being 0 for vertical lines, and the height being 0 for horizontal lines). It doesn't matter the direction you're scaling, it will disappear from view though it still shows up in the object tree.
2.  Another odd behavior (not sure if this is intended, though I don't see why it would be intentional) is that when creating a line, and want to constrain to a fixed angle (by pressing Shift key), I can't get it to constrain to either 0, or 90 deg. Only 45. 

**Version: 3.6.6733.23872**
[NaN_Error_when_creating_Hor-Ver_lines.zip](https://github.com/icons8/Lunacy/files/2088035/NaN_Error_when_creating_Hor-Ver_lines.zip)

Not sure if you're already aware of this, but it seems to be pretty consistent in my installation. See attached video for reference.

**Comment by yesarpit** [comment]
Same problem, cant open .lunacy files now. They seems corrupted.

**Comment by sergeychekmenev** [comment]
Hello! Thank you for your cooperation and interest to our project. We would appreciate it if you join our community forum on this page: https://community.icons8.com. Tons of useful info is already available on the forum! Bugs fixes, issues, discussions, announcements, articles, tips, links to videos, anticipated features, improvements. All hot topics in one place! Be a part of the community! Report bugs and join discussions! Help less experienced users! Access the most recent builds and send us documented feedback!
