### ISSUE TITLE
freeze on ubuntu 

### ISSUE THREAD

**Issue by nerdy-panda** [icons8/lunacy-docs#71]
when i install this software from snap or with .deb file and then run that i see this : 
![Screenshot_2022-11-29_05-34-48](https://user-images.githubusercontent.com/39291525/204440521-b56cdfa2-339e-4cca-8f18-d4b4d0351b0c.png)
lunacy sometime loaded with delay
but sometime is not loaded and freezed !!!

**Comment by duzyn** [comment]
+1

**Comment by Mikolaytis** [comment]
This is not our bug tracker. Here we accept only documentation-related issues.
Please, report new bugs here: https://community.icons8.com/c/lunacy/7

About issue - I hope it fixed in the recent updates. If not - contact as via community forum. Thanks!
