### ISSUE TITLE
Crash when pasting into a color text input.

### ISSUE THREAD

**Issue by langedechu** [icons8/lunacy-docs#77]
Hi. 

A few weeks ago, Lunacy started freezing when I copy/paste text inside a color text input. 

It happens only during the paste. 

It is not every time but when it happens it just ruins my workflow. 

Please let me know if you encountered the same issue.

Paul.

**Comment by Mikolaytis** [comment]
This is not our bug tracker. Here we accept only documentation-related issues.
Please, report new bugs here: https://community.icons8.com/c/lunacy/7

About issue - I hope it fixed in the recent updates. If not - contact as via community forum. Thanks!
