### ISSUE TITLE
Vectors/Text boxes randomly move/change their size/rotate on their own. CTRL + Z cannot undo those changes.

### ISSUE THREAD

**Issue by IvanTheNiceMan** [icons8/lunacy-docs#79]
**ISSUE:** Recently after downloading the latest lunacy releases, i noticed that sometimes when i _rotate objects/groups_, or do literally anything to them, they sometimes seem to **undo their size or rotation on their own**. It may happen constantly, or sometimes not happen at all.
Most of the time i was able to avoid this issue just by converting problematic shapes into vectors, but sometimes im just not able to do that.
Also such issue happens with text boxes too. Currently a 100% working method of avoiding that glitch is to just simply group the text box.

For example, If i will take a rectangle, first resize it to 1000 x 600, and then resize it to 700 x 500. And after that, i will create a complex shape, and turn it into a vector, the rectangle, that i have created previously, will immideatly change its size back to 1000 x 600.
And the only thing i can do in that situation is either change its size manualy to 700 x 500 again, or just save the file before every "succesful" change, and load the project file every time an error happens, because you simply cannot use CTRL + Z to solve this issue.

**Comment by Mikolaytis** [comment]
This is not our bug tracker. Here we accept only documentation-related issues.
Please, report new bugs here: https://community.icons8.com/c/lunacy/7

About issue - I hope it fixed in the recent updates. If not - contact as via community forum. Thanks!
