### ISSUE TITLE
Lunacy not opening!

### ISSUE THREAD

**Issue by DanTheDood** [icons8/lunacy-docs#80]
I installed lunacy on Windows, and it did work before, but it's not working anymore! I tried to reinstall it but that didn't work too!
My Device Specifications
```
Processor	Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz   1.19 GHz
Installed RAM	20.0 GB (19.7 GB usable)
```
And the crash info:
13:41:24.841 Launcher	Info	> Launched 9.4.2.5022 MsStore at 100% scale on Windows X64 with 8 cores and 20GB RAM. DeviceId: gNlk1CulgkKB-aMZcqmaIw
```
13:41:24.893 Account	Info	> Authorizing to HK_Prod
13:41:25.164 Api	Default	> Connection restoring: HK_Prod
13:41:25.177 Api	Default	> Main Connection is: HK_Prod
13:41:25.341 Settings	Info	> No settings in cloud
13:41:25.346 Push HK_Prod	Info	> Connecting
13:41:25.365 Account	Done	> Authorized to HK_Prod UserId:hS_eusPgBkuMQHXZ68_5dg
13:41:25.441 Push HK_Prod	Info	> Initializing
13:41:25.458 	Default	> HK_Prod Connected and Authorized
13:41:25.466 Push HK_Prod	Done	> Connected
13:41:25.831 SystemFonts	Info	> SystemFontFamilies: 6284, cacheFontFamilies: 0, shouldUpdate:True
13:41:26.660 Settings	Error	> Window load failed
13:41:27.485 Store	Info	> MS Store User Has 0 add-on licenses
13:41:27.770 Render	Default	> Scale: 1.25, DeviceScale: 1.25, SettingsScale: 1
```

**Comment by Mikolaytis** [comment]
This is not our bug tracker. Here we accept only documentation-related issues. 
Please, report new bugs here: https://community.icons8.com/c/lunacy/7

About issue - I hope it fixed in the recent updates. If not - contact as via community forum. Thanks!
