### ISSUE TITLE
Color changes in FREE JSON

### ISSUE THREAD

**Issue by Redigen** [icons8/lunacy-docs#83]
I want to automatically update the colors in the document by changing the colors in document.json. If I just fix the hex color, it will change in the color list, but the color is not updated automatically on the pages.
As I understand it, for this I need to change the color also in /pages/*.json, which is time consuming. I would like some kind of automatic updating of colors on pages from the document.json when opening the document.

I also wrote my own color palette generator, it generates colors in the document format.json, where I create my own id of 22 characters for each color.
"colorVariables": [
{
"id": "gSIsj5VKafKTlkeLEp_j8Q",
"name": "Primary",
"value": "8C5000"
}
…
When opening a document, Lunacy slightly changes my id, sometimes replaces one last character, for example Y with Q, etc. I wonder why this happens? But so far it doesn't bother me, even when writing new colors with other IDs, the colors are updated correctly in the color list, which is good.

**Comment by Mikolaytis** [comment]
This is not our bug tracker. Here we accept only documentation-related issues. 
Please, report new bugs here: https://community.icons8.com/c/lunacy/7

About topic: nice idea to fix it. Thought about it a while ago. Fixed it in 5 minutes. already available in beta. In release - next week.
