### ISSUE TITLE
Inquiry Regarding Distribution of Lunacy in Arch Linux CN Repository

### ISSUE THREAD

**Issue by everyx** [icons8/lunacy-docs#84]
Dear Lunacy Team,

I am a member of the [Arch Linux CN community](https://github.com/archlinuxcn), where we maintain a third-party software repository for Arch Linux users.

I am writing to inquire about the distribution of your software, Lunacy, within our repository. I have reviewed the [End-User License Agreement (EULA)](https://lunacy.docs.icons8.com/lunacy%20license/) and noted that it prohibits the reproduction, copying, distribution, resale, or any other commercial use of the software. However, the EULA does not explicitly address the terms regarding non-commercial use.

In our repository, we use a script to convert the official Lunacy deb package into an Arch Linux package for distribution. I would also like to mention that our repository's infrastructure is entirely open-source, and you can access and review the relevant conversion code [here](https://github.com/archlinuxcn/repo/tree/master/archlinuxcn/lunacy).

Given that our repository is intended for non-commercial purposes and aims to provide users with access to a variety of software, I would like to seek clarification on whether it would be permissible to distribute Lunacy in our repository under these circumstances.

Your guidance on this matter would be greatly appreciated, as we want to ensure that we comply with your licensing terms while providing valuable resources to our community.

Thank you for your time, and I look forward to your response.

Best regards

**Comment by Mikolaytis** [comment]
Hi, I'm lead developer and product owner of Lunacy. Huge thanks for adding Lunacy to your repository! Also thanks for asking us. Yes you understand license correctly. Non-commercial sharing of Lunacy is allowed and we are happy you've added our product! Thanks again!

**Comment by everyx** [comment]
> Hi, I'm lead developer and product owner of Lunacy. Huge thanks for adding Lunacy to your repository! Also thanks for asking us. Yes you understand license correctly. Non-commercial sharing of Lunacy is allowed and we are happy you've added our product! Thanks again!

@Mikolaytis Thanks for the clarification. BTW, Lunacy is a great product, thank you team for the great work. :)
