### ISSUE TITLE
Bug??!

### ISSUE THREAD

**Issue by bbxtudios** [icons8/lunacy-docs#85]
When I create a new project and add a canvas, then add any object, for example a square, or a button or whatever, and it stays in the background, there is no way to bring it to the front, then I save, reopen the project, and the object is already in the front.

In short, my canvas container layer is buggy and stays in the front.

Steps to follow.

1 - New file
2 - Click on the Marquee tool, select the Full HD preset (or any other)
3 - Select the Button Tool, or whatever and paint on the canvas.

Nothing is visible, but if I hover over where I put it, the selection borders are visible.
I save, close and reopen, and it works.

![Recording 2024-09-01 at 01 26 17](https://github.com/user-attachments/assets/91e30a6a-5772-4e58-9673-e29d4a78b861)

**Comment by Mikolaytis** [comment]
This is a bug. Huge thanks for a report with a video. For now - make a frame with drag-move creation, not by click on frame preset. thanks!

**Comment by Mikolaytis** [comment]
I will fix it now and in a few hours you can update your app to the beta. If you are using an app from msstore - update will be on the next weak in the 10.1 hotfix

**Comment by Mikolaytis** [comment]
fixed in beta. closing
